baseURL: "https://hatedpw.github.io/CyberQuackers/"
title: "CyberQuacker Rambling"
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true
  minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Search
          url: search/
          weight: 10
        - name: Tags
          url: tags/
          weight: 30
        - name: Archive
          url: archive/
          weight: 40

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: CyberQuacker Rambling
  description: "CyberQuacker Rambling"
  keywords: [Blog, Portfolio, PaperMod]
  author: CyberQuacker
  DateFormat: "January 2, 2006"
  defaultTheme: dark
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  profileMode:
    enabled: false # needs to be explicitly set
    title: CyberQuacker Rambling
    buttons:
      - name: Posts
        url: posts
      - name: Archives
        url: archives
      - name: Tags
        url: tags

  homeInfoParams:
    Title: "Hello"
    Content: I'm a australian penetration tester making my way through life one box at a time. 

  socialIcons:
    - name: github
      url: "https://github.com/hatedpw"
    - name: twitter
      url: "https://twitter.com/Hatedpw"

  editPost:
    URL: "https://github.com/hatedpw/CyberQuackers/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]